"""内置外部培训应用的 Docker 部署辅助服务。"""
from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen
from uuid import UUID

from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

from app.core.config import get_settings

_WORKSPACE_ROOT = Path(__file__).resolve().parents[3]


class EmbeddedAppDeploymentError(RuntimeError):
    """内置子程序部署流程失败。"""


@dataclass(frozen=True)
class EmbeddedAppRuntimeFiles:
    """记录单个内置子程序实例的运行目录和配置文件路径。"""

    deployment_dir: Path
    backend_env: Path
    frontend_env: Path
    compose_file: Path


def embedded_app_project_name(app_id: UUID | str) -> str:
    """生成 Docker Compose project 名称，确保同一应用多次操作命中同一组容器。"""
    prefix = str(app_id).replace("-", "")[:8].lower()
    return f"rag-embedded-training-{prefix}"


def embedded_app_runtime_files(app_id: UUID | str) -> EmbeddedAppRuntimeFiles:
    """返回内置培训应用实例的运行目录结构。"""
    settings = get_settings()
    deployment_dir = _resolve_workspace_path(settings.embedded_app_runtime_root) / str(app_id)
    return EmbeddedAppRuntimeFiles(
        deployment_dir=deployment_dir,
        backend_env=deployment_dir / "backend" / ".env",
        frontend_env=deployment_dir / "frontend" / ".env",
        compose_file=deployment_dir / "docker-compose.yml",
    )


def build_embedded_database_url(database_name: str) -> str:
    """基于主程序 PostgreSQL 连接串生成子程序独立数据库连接串。"""
    settings = get_settings()
    if not settings.database_url:
        raise EmbeddedAppDeploymentError("RAG_LAB_DATABASE_URL_REQUIRED")
    url = make_url(settings.database_url)
    drivername = "postgresql+psycopg2" if url.drivername.startswith("postgresql") else url.drivername
    return url.set(drivername=drivername, database=database_name).render_as_string(hide_password=False)


def ensure_embedded_database_exists(database_name: str) -> None:
    """在主程序 PostgreSQL 实例中创建子程序数据库；已存在时不做变更。"""
    if not re.fullmatch(r"[a-z][a-z0-9_]{0,62}", database_name):
        raise EmbeddedAppDeploymentError("EMBEDDED_APP_DATABASE_NAME_INVALID")
    settings = get_settings()
    if not settings.database_url:
        raise EmbeddedAppDeploymentError("RAG_LAB_DATABASE_URL_REQUIRED")
    admin_url = make_url(settings.database_url).set(database="postgres")
    engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    try:
        with engine.connect() as conn:
            exists = conn.execute(
                text("select 1 from pg_database where datname = :database_name"),
                {"database_name": database_name},
            ).scalar()
            if exists:
                return
            conn.execute(text(f'create database "{database_name}"'))
    finally:
        engine.dispose()


def write_embedded_training_runtime_files(
    *,
    app_id: UUID | str,
    database_name: str,
    platform_api_key: str,
    backend_port: int,
    frontend_port: int,
) -> EmbeddedAppRuntimeFiles:
    """写入 Docker Compose 和 .env 文件；系统 Key 明文只在创建应用时注入这里。"""
    settings = get_settings()
    files = embedded_app_runtime_files(app_id)
    files.backend_env.parent.mkdir(parents=True, exist_ok=True)
    files.frontend_env.parent.mkdir(parents=True, exist_ok=True)

    backend_env = "\n".join(
        [
            "# Generated by RAG-Lab embedded app deployment.",
            f"EXT_TRAINING_DATABASE_URL={build_embedded_database_url(database_name)}",
            f"EXT_TRAINING_PLATFORM_BASE_URL={settings.embedded_app_platform_base_url}",
            f"EXT_TRAINING_PLATFORM_APP_ID={app_id}",
            f"EXT_TRAINING_PLATFORM_API_KEY={platform_api_key}",
            f"EXT_TRAINING_BACKEND_PORT={backend_port}",
            "",
        ]
    )
    frontend_env = "\n".join(
        [
            "# Generated by RAG-Lab embedded app deployment.",
            f"VITE_EXT_TRAINING_BACKEND_PROXY_TARGET=http://backend:{backend_port}",
            f"VITE_EXT_TRAINING_FRONTEND_PORT={frontend_port}",
            "",
        ]
    )
    compose = _build_compose_file(settings, backend_port, frontend_port)
    files.backend_env.write_text(backend_env, encoding="utf-8")
    files.frontend_env.write_text(frontend_env, encoding="utf-8")
    files.compose_file.write_text(compose, encoding="utf-8")
    source_backend_env = _resolve_workspace_path(settings.embedded_app_source_root) / "backend" / ".env"
    source_backend_env.parent.mkdir(parents=True, exist_ok=True)
    source_backend_env.write_text(backend_env, encoding="utf-8")
    return files


def run_compose_action(app_id: UUID | str, action: str) -> subprocess.CompletedProcess[str]:
    """执行 Docker Compose 动作；兼容 Windows Docker Desktop 和 docker-compose。"""
    if action not in {"up", "stop", "down", "restart"}:
        raise EmbeddedAppDeploymentError("EMBEDDED_APP_COMPOSE_ACTION_INVALID")
    files = embedded_app_runtime_files(app_id)
    if not files.compose_file.exists():
        raise EmbeddedAppDeploymentError("EMBEDDED_APP_RUNTIME_FILES_MISSING")
    args = ["up", "-d"] if action == "up" else [action]
    return _run_compose(files.deployment_dir, embedded_app_project_name(app_id), args)


def check_embedded_http_health(url: str, timeout_seconds: float = 3.0) -> bool:
    """通过 HTTP 探测子程序健康状态，失败时返回 False 而不是抛出网络异常。"""
    try:
        request = Request(url, method="GET")
        with urlopen(request, timeout=timeout_seconds) as response:
            return 200 <= response.status < 500
    except (OSError, URLError):
        return False


def _build_compose_file(settings, backend_port: int, frontend_port: int) -> str:
    """生成单实例 Compose 文件，端口写死到实例文件中避免变量替换歧义。"""
    return f"""services:
  backend:
    image: {settings.embedded_app_backend_image}
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "{backend_port}:{backend_port}"
    command: ["sh", "-c", "alembic upgrade head && python -m uvicorn app.main:app --host 0.0.0.0 --port {backend_port}"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: {settings.embedded_app_frontend_image}
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "{frontend_port}:{frontend_port}"
    command: ["sh", "-c", "npm run dev -- --host 0.0.0.0 --port {frontend_port}"]
"""


def _run_compose(
    deployment_dir: Path,
    project_name: str,
    args: list[str],
) -> subprocess.CompletedProcess[str]:
    """优先执行 docker compose，失败后回退 docker-compose。"""
    commands = [
        ["docker", "compose", "-p", project_name, *args],
        ["docker-compose", "-p", project_name, *args],
    ]
    last_error: FileNotFoundError | subprocess.CalledProcessError | None = None
    for command in commands:
        try:
            return subprocess.run(
                command,
                cwd=deployment_dir,
                check=True,
                capture_output=True,
                text=True,
                encoding="utf-8",
            )
        except FileNotFoundError as exc:
            last_error = exc
        except subprocess.CalledProcessError as exc:
            last_error = exc
            break
    message = str(last_error) if last_error else "Docker Compose command failed."
    raise EmbeddedAppDeploymentError(message)


def _resolve_workspace_path(value: str) -> Path:
    """将配置路径解析为绝对路径；相对路径固定按仓库根目录解释。"""
    path = Path(value)
    return path if path.is_absolute() else _WORKSPACE_ROOT / path
